[package]
name = "auto-agent"
version = "0.1.0"
edition = "2021"

[dependencies]
tauri = { version = "2.0.0-beta", features = [] }
tauri-plugin-fs = "2.0.0-beta"
serde_json = "1.0"

[build-dependencies]
tauri-build = { version = "2.0.0-beta", features = [] }
